<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>15&nbsp; Mobilidade e Acessibilidade – Censo Demográfico no R</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./16-renda-e-trabalho.html" rel="next">
<link href="./14-saneamento.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-12eeb4b20e9f5a2b0bfc604bfaf942bb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-acff971833d9769290026d534105daaa.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-12eeb4b20e9f5a2b0bfc604bfaf942bb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>


<link rel="stylesheet" href="custom.css">
<meta property="og:title" content="15&nbsp; Mobilidade e Acessibilidade – Censo Demográfico no R">
<meta property="og:description" content="">
<meta property="og:image" content="https://pedreirajr.github.io/rcensolivro/15-mobilidade_files/figure-html/fig-mob-posse-1.png">
<meta property="og:site_name" content="Censo Demográfico no R">
<meta property="og:image:height" content="499">
<meta property="og:image:width" content="1344">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./12-demografia.html">PARTE 3: APLICAÇÕES TERRITORIAIS</a></li><li class="breadcrumb-item"><a href="./15-mobilidade.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Mobilidade e Acessibilidade</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Censo Demográfico no R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo escuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefácio</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">PARTE 1: ANÁLISE EXPLORATÓRIA DE DADOS COM R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-introducao-ao-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introdução ao R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-estatistica-descritiva.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Estatística Descritiva</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-manipulacao-de-dados-tabulares.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Manipulação de Dados Tabulares</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-visualizacao-de-dados-tabulares.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Visualização de Dados Tabulares</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-dados-geograficos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Dados Geográficos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">PARTE 2: O CENSO DEMOGRÁFICO E SEUS PRODUTOS</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6-conceitos-e-metodos-censo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Censo Demográfico: Conceitos e Métodos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-agregados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Agregados por Setor Censitário</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8-microdados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Microdados da Amostra</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./9-grade-estatistica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Grade Estatística</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-cnefe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">CNEFE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-entorno.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Características Urbanísticas do Entorno dos Domicílios</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">PARTE 3: APLICAÇÕES TERRITORIAIS</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-demografia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Demografia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-habitacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Habitação</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-saneamento.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Saneamento e Drenagem Urbana</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-mobilidade.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Mobilidade e Acessibilidade</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-renda-e-trabalho.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Renda e Trabalho</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referências</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice do Capítulo</h2>
   
  <ul>
  <li><a href="#sec-mob-intro" id="toc-sec-mob-intro" class="nav-link active" data-scroll-target="#sec-mob-intro"><span class="header-section-number">15.1</span> Introdução</a></li>
  <li><a href="#sec-mob-edicoes" id="toc-sec-mob-edicoes" class="nav-link" data-scroll-target="#sec-mob-edicoes"><span class="header-section-number">15.2</span> O que cada edição do Censo permite investigar</a></li>
  <li><a href="#sec-mob-dados" id="toc-sec-mob-dados" class="nav-link" data-scroll-target="#sec-mob-dados"><span class="header-section-number">15.3</span> Estruturação dos microdados da amostra de 2010</a></li>
  <li><a href="#sec-mob-veiculos" id="toc-sec-mob-veiculos" class="nav-link" data-scroll-target="#sec-mob-veiculos"><span class="header-section-number">15.4</span> Posse de automóvel e motocicleta</a></li>
  <li><a href="#sec-mob-local" id="toc-sec-mob-local" class="nav-link" data-scroll-target="#sec-mob-local"><span class="header-section-number">15.5</span> Categorias de local de trabalho</a></li>
  <li><a href="#sec-mob-tempo" id="toc-sec-mob-tempo" class="nav-link" data-scroll-target="#sec-mob-tempo"><span class="header-section-number">15.6</span> Tempo de deslocamento</a></li>
  <li><a href="#sec-mob-acessibilidade" id="toc-sec-mob-acessibilidade" class="nav-link" data-scroll-target="#sec-mob-acessibilidade"><span class="header-section-number">15.7</span> A infraestrutura para a acessibilidade</a>
  <ul>
  <li><a href="#sec-mob-mapas" id="toc-sec-mob-mapas" class="nav-link" data-scroll-target="#sec-mob-mapas"><span class="header-section-number">15.7.1</span> Onde está a infraestrutura</a></li>
  </ul></li>
  <li><a href="#sec-mob-sintese" id="toc-sec-mob-sintese" class="nav-link" data-scroll-target="#sec-mob-sintese"><span class="header-section-number">15.8</span> Síntese</a></li>
  <li><a href="#sec-mob-exercicios" id="toc-sec-mob-exercicios" class="nav-link" data-scroll-target="#sec-mob-exercicios"><span class="header-section-number">15.9</span> Exercícios</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./12-demografia.html">PARTE 3: APLICAÇÕES TERRITORIAIS</a></li><li class="breadcrumb-item"><a href="./15-mobilidade.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Mobilidade e Acessibilidade</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Mobilidade e Acessibilidade</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-mob-intro" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="sec-mob-intro"><span class="header-section-number">15.1</span> Introdução</h2>
<p>Deslocar-se é uma necessidade urbana cotidiana e talvez uma das mais desigualmente atendidas. Indivíduos de locais não tão distantes entre si podem enfrentar condições bem distintas a depender do seu destino e dos recursos que dispõem para tanto. Por mais que existam pesquisas de origem e destino para descrever esse fenômeno com um detalhe que nenhuma outra fonte alcança, elas geralmente são realizadas em cidades e regiões metropolitanas de maior porte e com maiores recursos. Por outro lado, o Censo cobre todo o território nacional com periodicidade regular, e por isso continua sendo a única base que permite comparar a mobilidade entre todos municípios brasileiros.</p>
<p>O título deste capítulo traz dois termos porque os dados do Censo podem responder a duas perguntas distintas nesse contexto. A primeira é sobre o <strong>comportamento de deslocamento</strong>, a exemplo de quanto tempo as pessoas gastam e quais recursos dispõem para chegar lá. Essa é a pergunta da mobilidade, e ela é respondida pelos microdados da amostra. A segunda é sobre a infraestrutura de transportes disponível para <em>acessar</em> os diferentes locais do município. Essa é a pergunta da <strong>acessibilidade</strong>, e ela é respondida pela Pesquisa Urbanística do Entorno dos Domicílios.</p>
<p>Esta segunda pergunta é importante, pois uma cidade proporciona melhores condições de vida a seus habitantes quando existe uma base física de qualidade para estes deslocamentos. Essa base é feita de calçada, rampas para cadeirantes, vias pavimentadas e abundância pontos de parada para o transporte coletivo. Onde essa base é deficiente, o deslocamento continua acontecendo, porque as pessoas precisam trabalhar e estudar, mas passa a ser feito com maior esforço, risco e tempo. Medir o comportamento sem medir a infraestrutura descreve o resultado e esconde a condição que o produziu.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Como o termo acessibilidade é usado neste capítulo
</div>
</div>
<div class="callout-body-container callout-body">
<p>No planejamento de transportes, <strong>acessibilidade</strong> designa a facilidade com que se alcança um destino a partir de um lugar, e é uma função, principalmente, da rede de transporte e da distribuição das atividades no território. Calculá-la nesse sentido estrito exige matrizes de tempo de viagem e a localização das oportunidades de emprego, saúde e educação, insumos que o Censo Demográfico não fornece.</p>
<p>Não é isso que faremos aqui. Este capítulo trata da <strong>camada física</strong> sobre a qual qualquer medida de acessibilidade se apoia, ou seja, da infraestrutura que torna o território percorrível. Quando dissermos que um setor censitário é mais acessível que outro, estaremos afirmando algo verificável nos dados, que é a maior presença de calçada, de pavimentação, de rampa e de ponto de ônibus no entorno imediato dos seus domicílios.</p>
<p>O termo carrega ainda um segundo sentido, o da <strong>acessibilidade universal</strong>, que trata das condições de circulação de pessoas com deficiência e mobilidade reduzida. Esse sentido também aparece nos dados, na rampa para cadeirante e no obstáculo na calçada, tratados na <a href="#sec-mob-acessibilidade" class="quarto-xref"><span>Seção 15.7</span></a>. Os dois sentidos convergem no mesmo objeto, que é a calçada, e é por isso que ela ocupa o centro da segunda metade do capítulo.</p>
</div>
</div>
<p>O município escolhido para este capítulo é <strong>Salvador (BA)</strong>, que possui estrutura socioespacial fortemente polarizada entre a orla atlântica e a chamada área do miolo e o Subúrbio Ferroviário. Conforme será visto, os resultados produzem contrastes internos marcantes em qualquer indicador que produziremos.</p>
<p>Comecemos carregando os pacotes usados ao longo do capítulo<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(censobr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geobr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(srvyr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="sec-mob-edicoes" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="sec-mob-edicoes"><span class="header-section-number">15.2</span> O que cada edição do Censo permite investigar</h2>
<!-- mudar aqui quando chegarem os microdados -->
<p>Antes de qualquer cálculo, vamos explorar o que existe. Este é o capítulo do livro em que a diferença entre as edições mais restringe o que se pode fazer, e ignorá-la levaria a procurar variáveis que não existem ou a comparar quesitos que mudaram de redação. A <a href="#tbl-mob-edicoes" class="quarto-xref">Tabela&nbsp;<span>15.1</span></a> confronta os quesitos de deslocamento dos dois Questionários da Amostra.</p>
<div class="cell">
<div id="tbl-mob-edicoes" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mob-edicoes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;15.1: Quesitos de mobilidade nos Questionários da Amostra dos Censos 2010 e 2022.
</figcaption>
<div aria-describedby="tbl-mob-edicoes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 34%">
<col style="width: 26%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Quesito</th>
<th style="text-align: center;">2010</th>
<th style="text-align: center;">2022</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Posse de motocicleta</td>
<td style="text-align: center;"><code>V0221</code></td>
<td style="text-align: center;">Não investigado</td>
</tr>
<tr class="even">
<td style="text-align: left;">Posse de automóvel</td>
<td style="text-align: center;"><code>V0222</code></td>
<td style="text-align: center;">Não investigado</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Município onde trabalha</td>
<td style="text-align: center;"><code>V0660</code>, <code>V6604</code></td>
<td style="text-align: center;">Quesito 15.01</td>
</tr>
<tr class="even">
<td style="text-align: left;">Retorna do trabalho para casa</td>
<td style="text-align: center;"><code>V0661</code>, diariamente</td>
<td style="text-align: center;">Quesito 15.02, três dias ou mais</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tempo de deslocamento</td>
<td style="text-align: center;"><code>V0662</code>, cinco faixas</td>
<td style="text-align: center;">Quesito 15.03, horas e minutos</td>
</tr>
<tr class="even">
<td style="text-align: left;">Modo de transporte principal</td>
<td style="text-align: center;">Não investigado</td>
<td style="text-align: center;">Quesito 15.04, 14 categorias</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Deslocamento para estudo</td>
<td style="text-align: center;">Não investigado</td>
<td style="text-align: center;">Bloco 13</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Três leituras importam nessa tabela. A primeira é que <strong>2022 eliminou a posse de veículos</strong>. O bloco de bens duráveis do Questionário da Amostra ficou reduzido a dois itens, máquina de lavar roupa e acesso à internet, e automóvel e motocicleta saíram. Não haverá continuidade para esse indicador.</p>
<p>A segunda é que, em contrapartida, <strong>2022 ganhou o modo de transporte</strong>, que nunca existiu em censo brasileiro anterior. Quando os microdados forem divulgados, será possível descrever a divisão modal do deslocamento casa-trabalho para qualquer município do país.</p>
<p>A terceira é mais sutil e mais perigosa. O quesito sobre retorno ao domicílio mudou de redação, de “retorna do trabalho para casa <strong>diariamente</strong>” em 2010 para “retorna do trabalho para casa <strong>três dias ou mais</strong> na semana” em 2022. São perguntas diferentes, e comparar as duas respostas produziria uma variação que pode trazer imprecisões importantes sobre esse aspecto.</p>
<p>Como os microdados de 2022 ainda não foram divulgados, todo o comportamento de deslocamento deste capítulo vem de 2010. Todavia, a infraestrutura que vem do Entorno é de 2022, e a <a href="#sec-mob-acessibilidade" class="quarto-xref"><span>Seção 15.7</span></a> explica por que ela não é comparada com a de 2010.</p>
</section>
<section id="sec-mob-dados" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="sec-mob-dados"><span class="header-section-number">15.3</span> Estruturação dos microdados da amostra de 2010</h2>
<p>Para os microdados de 2010, precisamos do código do município e da malha de áreas de ponderação dessas áreas, que servirá de base para todos os mapas da primeira metade do capítulo.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Código IBGE do município:</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>salvador <span class="ot">&lt;-</span> <span class="fu">lookup_muni</span>(<span class="at">name_muni =</span> <span class="st">"Salvador"</span>, <span class="at">year =</span> <span class="dv">2022</span>)<span class="sc">$</span>code_muni</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Malha de áreas de ponderação de 2010, base dos mapas da primeira metade:</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>ap_ssa <span class="ot">&lt;-</span> <span class="fu">read_weighting_area</span>(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">code_weighting =</span> salvador,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">year           =</span> <span class="dv">2010</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">simplified     =</span> <span class="cn">FALSE</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="do">## Vetor de códigos, p/ filtrar os microdados:</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>ap_cods <span class="ot">&lt;-</span> ap_ssa <span class="sc">|&gt;</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(code_weighting)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(ap_cods)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 62</code></pre>
</div>
</div>
<p>Temos sessenta e duas áreas para um município de mais de dois milhões e meio de habitantes em 2010, o que nos dá uma resolução espacial razoável a ser explorada. Neste capítulo, utilizaremos tanto o arquivo de <strong>indivíduos</strong> quanto o de <strong>domicílio</strong> dos microdados. Isso porque a posse de veículos é característica do domicílio e o tempo de deslocamento e o local de trabalho são características da pessoa e estão no arquivo de pessoas.</p>
<p>Começamos pelos domicílios. Além das duas variáveis de interesse, pedimos <code>V4001</code>, que identifica o tipo de domicílio, por uma razão que ficará clara adiante.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Selecionando colunas dos microdados de domicílio:</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>cols_dom <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"V0300"</span>,          <span class="co"># Identificador do domicílio</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"V0010"</span>,          <span class="co"># Peso amostral calibrado</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"code_weighting"</span>, <span class="co"># Área de ponderação</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"V4001"</span>,          <span class="co"># Tipo de domicílio</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"V0221"</span>,          <span class="co"># Motocicleta para uso particular</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"V0222"</span>           <span class="co"># Automóvel para uso particular</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="do">## Lendo microdados, só das áreas de ponderação de Salvador:</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>md_dom <span class="ot">&lt;-</span> <span class="fu">read_households</span>(<span class="at">year =</span> <span class="dv">2010</span>, <span class="at">columns =</span> cols_dom) <span class="sc">|&gt;</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(code_weighting <span class="sc">%in%</span> ap_cods) <span class="sc">|&gt;</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect</span>()</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="do">## Conferindo as respostas de posse de automóvel:</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>md_dom <span class="sc">|&gt;</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(V0222)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  V0222     n
  &lt;chr&gt; &lt;int&gt;
1 1     12295
2 2     31594
3 &lt;NA&gt;    613</code></pre>
</div>
</div>
<p>Há registros sem resposta, e antes de aplicar <code>na.rm = TRUE</code> convém entender de onde vêm. O cruzamento com o tipo de domicílio resolve a dúvida.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Cruzando os ausentes com o tipo de domicílio:</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>md_dom <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(V4001) <span class="sc">|&gt;</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">registros       =</span> <span class="fu">n</span>(),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sem_resposta    =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(V0222))</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  V4001 registros sem_resposta
  &lt;chr&gt;     &lt;int&gt;        &lt;int&gt;
1 01        43889            0
2 05          160          160
3 06          453          453</code></pre>
</div>
</div>
<p>Todos os ausentes estão nos tipos 05 e 06, que são o domicílio particular improvisado e o domicílio coletivo. O quesito de bens duráveis só é aplicado a <strong>domicílios particulares permanentes</strong>, de código 01, e por isso os demais chegam em branco. É meramente um caso de “não se aplica”.</p>
<p>A conduta correta, portanto, não é descartar os ausentes com <code>na.rm = TRUE</code>, e sim restringir a análise ao universo em que a pergunta foi feita. As duas coisas produzem o mesmo número neste caso, mas apenas a segunda deixa o universo explícito para quem lê.</p>
<p>Esse recorte, porém, não é aplicado à tabela. Declaramos o desenho amostral sobre todos os domicílios lidos, na forma apresentada no Capítulo 8, e só então restringimos o universo filtrando o próprio desenho. O objeto resultante, que chamaremos de <code>pa_dpp</code>, mantém a estratificação e a correção de população finita originais e passa a tratar os domicílios particulares permanentes como um domínio dentro da amostra, que é o que eles de fato são. A <a href="#sec-mob-tempo" class="quarto-xref"><span>Seção 15.6</span></a> retoma essa distinção em detalhe, quando o universo em jogo for o das pessoas que se deslocam para o trabalho.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Total de domicílios por área de ponderação, p/ a correção de população finita:</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>dom_ap <span class="ot">&lt;-</span> md_dom <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(code_weighting) <span class="sc">|&gt;</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n_dom =</span> <span class="fu">sum</span>(V0010))</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Levando esse total para cada registro:</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>md_dom <span class="ot">&lt;-</span> md_dom <span class="sc">|&gt;</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(dom_ap, <span class="at">by =</span> <span class="fu">join_by</span>(code_weighting))</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="do">## Produzindo o plano amostral para os domicílios:</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>pa_dom <span class="ot">&lt;-</span> md_dom <span class="sc">|&gt;</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">strata  =</span> code_weighting,</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> V0010,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">fpc     =</span> n_dom</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="do">## Restringindo o universo aos domicílios particulares permanentes:</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>pa_dpp <span class="ot">&lt;-</span> pa_dom <span class="sc">|&gt;</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(V4001 <span class="sc">==</span> <span class="st">"01"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>O arquivo de pessoas segue a mesma lógica, com a diferença já discutida no Capítulo 8, que é a necessidade de declarar o domicílio como unidade de conglomeração. Pedimos as três variáveis de deslocamento que serão usadas adiante.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Selecionando colunas dos microdados de pessoas:</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>cols_pes <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"V0300"</span>,          <span class="co"># Identificador do domicílio (conglomerado)</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"V0010"</span>,          <span class="co"># Peso amostral calibrado</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"code_weighting"</span>, <span class="co"># Área de ponderação</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"V0660"</span>,          <span class="co"># Município ou país onde trabalha</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"V0661"</span>,          <span class="co"># Retorna do trabalho para casa diariamente</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"V0662"</span>           <span class="co"># Tempo habitual de deslocamento até o trabalho</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="do">## Lendo microdados de pessoas:</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>md_pes <span class="ot">&lt;-</span> <span class="fu">read_population</span>(<span class="at">year =</span> <span class="dv">2010</span>, <span class="at">columns =</span> cols_pes) <span class="sc">|&gt;</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(code_weighting <span class="sc">%in%</span> ap_cods) <span class="sc">|&gt;</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect</span>()</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="do">## Total de pessoas por área de ponderação, p/ a correção de população finita:</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>pes_ap <span class="ot">&lt;-</span> md_pes <span class="sc">|&gt;</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(code_weighting) <span class="sc">|&gt;</span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n_ind =</span> <span class="fu">sum</span>(V0010))</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="do">## Levando esse total para cada registro:</span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>md_pes <span class="ot">&lt;-</span> md_pes <span class="sc">|&gt;</span></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(pes_ap, <span class="at">by =</span> <span class="fu">join_by</span>(code_weighting))</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a><span class="do">## Produzindo o plano amostral para os indivíduos:</span></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>pa_pes <span class="ot">&lt;-</span> md_pes <span class="sc">|&gt;</span></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_survey_design</span>(</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">ids     =</span> V0300,</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">strata  =</span> code_weighting,</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">weights =</span> V0010,</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">fpc     =</span> n_ind</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Com os dois desenhos amostrais declarados, podemos calcular.</p>
</section>
<section id="sec-mob-veiculos" class="level2" data-number="15.4">
<h2 data-number="15.4" class="anchored" data-anchor-id="sec-mob-veiculos"><span class="header-section-number">15.4</span> Posse de automóvel e motocicleta</h2>
<p>A posse de veículo não mede mobilidade, mas uma <em>possibilidade</em>, configurando, inclusive, uma medida importante de acessibilidade. Um domicílio com automóvel tem uma alternativa de deslocamento que outro que não possui, e essa diferença costuma influenciar consideravelmente todo o restante, do tempo de viagem à sensibilidade quanto à qualidade do transporte público. Comecemos pelo retrato municipal, com os intervalos de confiança que o desenho amostral exige.</p>
<p>Os dois veículos vêm de variáveis diferentes, e por isso cada um exige uma chamada própria a <code>survey_mean()</code>. Para levá-los ao mesmo gráfico, empilhamos os dois resultados com <code>bind_rows()</code>, acrescentando em cada um a coluna que identifica o veículo. O formato longo resultante, com uma linha por veículo, é o que o <code>ggplot2</code> espera, e o resultado aparece na <a href="#fig-mob-posse" class="quarto-xref">Figura&nbsp;<span>15.1</span></a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Estimando a posse dos dois veículos e empilhando os resultados:</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>posse_mun <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  pa_dpp <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">proporcao =</span> <span class="fu">survey_mean</span>(V0222 <span class="sc">==</span> <span class="st">"1"</span>, <span class="at">vartype =</span> <span class="st">"ci"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">veiculo =</span> <span class="st">"Automóvel"</span>),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  pa_dpp <span class="sc">|&gt;</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">proporcao =</span> <span class="fu">survey_mean</span>(V0221 <span class="sc">==</span> <span class="st">"1"</span>, <span class="at">vartype =</span> <span class="st">"ci"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">veiculo =</span> <span class="st">"Motocicleta"</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>posse_mun</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  proporcao proporcao_low proporcao_upp veiculo    
      &lt;dbl&gt;         &lt;dbl&gt;         &lt;dbl&gt; &lt;chr&gt;      
1    0.286         0.282         0.290  Automóvel  
2    0.0575        0.0552        0.0597 Motocicleta</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Gráfico de barras com as barras de erro do IC 95%:</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(posse_mun, <span class="fu">aes</span>(<span class="at">x =</span> veiculo, <span class="at">y =</span> proporcao,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">ymin =</span> proporcao_low, <span class="at">ymax =</span> proporcao_upp)) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>, <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">width =</span> <span class="fl">0.15</span>, <span class="at">color =</span> <span class="st">"orange"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_percent</span>(<span class="at">decimal.mark =</span> <span class="st">","</span>)) <span class="sc">+</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Domicílios particulares permanentes"</span>) <span class="sc">+</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-mob-posse" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-mob-posse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;15.1: Proporção de domicílios particulares permanentes de Salvador (BA) com automóvel e com motocicleta, microdados da amostra do Censo 2010. Barras de erro indicam IC 95%.
</figcaption>
<div aria-describedby="fig-mob-posse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15-mobilidade_files/figure-html/fig-mob-posse-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>Pouco menos de três em cada dez domicílios particulares permanentes de Salvador tinham automóvel em 2010, e a motocicleta aparecia em cerca de um em cada dezoito. As barras de erro quase desaparecem sobre as colunas, e é esse o resultado esperado, uma vez que a amostra do Censo é grande e o cálculo foi feito para o município inteiro. Quando descermos à área de ponderação, com uma fração dos domicílios em cada uma, eles voltarão a ter tamanho suficiente para exigir atenção.</p>
<p>O interesse está na distribuição interna. Os dois mapas da <a href="#fig-veiculos" class="quarto-xref">Figura&nbsp;<span>15.2</span></a> trazem cada veículo em uma escala própria, porque as amplitudes são muito diferentes e uma escala comum apagaria o padrão da motocicleta.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Sumarização dos que possuem automóvel e motocicleta:</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>veic_ap <span class="ot">&lt;-</span> pa_dpp <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(code_weighting) <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">automovel   =</span> <span class="fu">survey_mean</span>(V0222 <span class="sc">==</span> <span class="st">"1"</span>),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">motocicleta =</span> <span class="fu">survey_mean</span>(V0221 <span class="sc">==</span> <span class="st">"1"</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="do">## Junção com a malha de áreas de ponderação:</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>veic_geo <span class="ot">&lt;-</span> ap_ssa <span class="sc">|&gt;</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(veic_ap, <span class="at">by =</span> <span class="fu">join_by</span>(code_weighting))</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="do">## Produzindo os gráficos:</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="do">## O tema é guardado em um objeto porque se repete em todos os mapas do capítulo</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>tema_mapa <span class="ot">&lt;-</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text =</span> <span class="fu">element_blank</span>(), <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid =</span> <span class="fu">element_blank</span>())</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>mapa_auto <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(veic_geo) <span class="sc">+</span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> <span class="dv">100</span> <span class="sc">*</span> automovel), <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"Blues"</span>, <span class="at">direction =</span> <span class="dv">1</span>,</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>                       <span class="at">name =</span> <span class="st">"% dos</span><span class="sc">\n</span><span class="st">domicílios"</span>, <span class="at">na.value =</span> <span class="st">"gray90"</span>) <span class="sc">+</span></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">expand =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">"Automóvel"</span>) <span class="sc">+</span></span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>  tema_mapa</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>mapa_moto <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(veic_geo) <span class="sc">+</span></span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> <span class="dv">100</span> <span class="sc">*</span> motocicleta), <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"Oranges"</span>, <span class="at">direction =</span> <span class="dv">1</span>,</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>                       <span class="at">name =</span> <span class="st">"% dos</span><span class="sc">\n</span><span class="st">domicílios"</span>, <span class="at">na.value =</span> <span class="st">"gray90"</span>) <span class="sc">+</span></span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">expand =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">"Motocicleta"</span>) <span class="sc">+</span></span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>  tema_mapa</span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>mapa_auto <span class="sc">/</span> mapa_moto</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-veiculos" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-veiculos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;15.2: Domicílios particulares permanentes com automóvel (acima) e com motocicleta (abaixo), por área de ponderação, Salvador (BA), microdados da amostra do Censo 2010.
</figcaption>
<div aria-describedby="fig-veiculos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15-mobilidade_files/figure-html/fig-veiculos-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>Os dois mapas mostram uma inconveniência cartográfica que precisa ser discutida preliminarmente. Uma única área de ponderação, a de código <code>2927408005038</code>, ocupa quase metade da figura e empurra o restante da cidade para o canto inferior direito. Ela tem mais de quatrocentos quilômetros quadrados porque incorpora as águas da Baía de Todos-os-Santos, que estão dentro dos limites de Salvador, e os bairros de Paripe e São Tomé, no Subúrbio Ferroviário, onde se encontra toda a sua população.</p>
<p>As ilhas habitadas do município não pertencem a essa área. Elas formam a área de ponderação <code>2927408005027</code>, que aparece nos dois recortes claros desenhados no alto de cada mapa, reunindo Ilha de Maré, Ilha dos Frades, Ilha de Santo Antônio e Ilha de Bom Jesus dos Passos. É ela que registra a menor posse de automóvel de todo o município, e o valor não expressa somente privação de renda, porque nas ilhas de Salvador praticamente não há por onde dirigir. O mesmo problema de enquadramento reaparece com os setores censitários de 2022, e a <a href="#sec-mob-mapas" class="quarto-xref"><span>Seção 15.7.1</span></a> mostra como resolvê-lo.</p>
<p>Descontada a distorção do enquadramento, o padrão do automóvel é nítido, com as proporções mais altas concentradas na ponta sul da península e ao longo da orla atlântica, e um declínio contínuo em direção ao miolo e ao norte do município, compreendendo também a região do Subúrbio Ferroviário. A motocicleta desenha um padrão aproximadamente invertido, com as maiores proporções no Subúrbio Ferroviário e algumas áreas do miolo, com as menores exatamente onde o automóvel é mais frequente. Convém não exagerar a leitura dessa inversão, porque as duas escalas são incomparáveis em magnitude, conforme o resultado abaixo deixa claro.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>veic_ap <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">auto_minimo =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">min</span>(automovel),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">auto_maximo =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">max</span>(automovel),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">moto_minimo =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">min</span>(motocicleta),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">moto_maximo =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">max</span>(motocicleta)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  auto_minimo auto_maximo moto_minimo moto_maximo
        &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
1       0.487        84.8       0.178        8.23</code></pre>
</div>
</div>
<p>A posse de automóvel varia de menos de um por cento a quase oitenta e cinco por cento entre as áreas de ponderação de um mesmo município. É uma amplitude de mais de oitenta pontos percentuais, e ela expressa, dentro dos limites de Salvador, distâncias que costumam ser descritas comparando países. A motocicleta varia num intervalo de oito pontos, e a leitura correta é que ela funciona como alternativa de menor custo em algumas áreas, sem nunca ter alcançado a difusão que o automóvel tem na orla até 2010.</p>
<p>Guardadas essas proporções, resta saber para onde essas pessoas se deslocavam, e é do local de trabalho que trata a próxima seção.</p>
</section>
<section id="sec-mob-local" class="level2" data-number="15.5">
<h2 data-number="15.5" class="anchored" data-anchor-id="sec-mob-local"><span class="header-section-number">15.5</span> Categorias de local de trabalho</h2>
<p>A variável <code>V0660</code> informa onde a pessoa ocupada exercia o trabalho principal, e ela precisa vir antes do tempo de deslocamento por uma razão prática. É ela que define quem se desloca, e portanto quem entra no denominador do indicador de tempo. A <a href="#tbl-mob-local-trabalho" class="quarto-xref">Tabela&nbsp;<span>15.2</span></a> traz a sua distribuição.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>pa_pes <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(V0660)) <span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">local =</span> <span class="fu">factor</span>(</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>      V0660,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>, <span class="st">"4"</span>, <span class="st">"5"</span>),</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No próprio domicílio"</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Apenas neste município, fora do domicílio"</span>,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Em outro município"</span>, <span class="st">"Em país estrangeiro"</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Em mais de um município ou país"</span>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(local) <span class="sc">|&gt;</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">proporcao =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span> <span class="st">"ci"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Local de trabalho"</span>, <span class="st">"Proporção"</span>,</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"IC 95%, limite inferior"</span>, <span class="st">"IC 95%, limite superior"</span>),</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">4</span>,</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">decimal.mark =</span> <span class="st">","</span>)</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-mob-local-trabalho" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mob-local-trabalho-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;15.2: Distribuição das pessoas ocupadas de Salvador (BA) segundo o local de trabalho, microdados da amostra do Censo 2010.
</figcaption>
<div aria-describedby="tbl-mob-local-trabalho-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 42%">
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Local de trabalho</th>
<th style="text-align: right;">Proporção</th>
<th style="text-align: right;">IC 95%, limite inferior</th>
<th style="text-align: right;">IC 95%, limite superior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No próprio domicílio</td>
<td style="text-align: right;">0,2357</td>
<td style="text-align: right;">0,2311</td>
<td style="text-align: right;">0,2403</td>
</tr>
<tr class="even">
<td style="text-align: left;">Apenas neste município, fora do domicílio</td>
<td style="text-align: right;">0,7104</td>
<td style="text-align: right;">0,7055</td>
<td style="text-align: right;">0,7152</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Em outro município</td>
<td style="text-align: right;">0,0481</td>
<td style="text-align: right;">0,0462</td>
<td style="text-align: right;">0,0500</td>
</tr>
<tr class="even">
<td style="text-align: left;">Em país estrangeiro</td>
<td style="text-align: right;">0,0005</td>
<td style="text-align: right;">0,0003</td>
<td style="text-align: right;">0,0007</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Em mais de um município ou país</td>
<td style="text-align: right;">0,0055</td>
<td style="text-align: right;">0,0049</td>
<td style="text-align: right;">0,0061</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Duas informações saem daí. A primeira é que cerca de sete em cada dez pessoas ocupadas trabalhavam no próprio município e fora de casa, e que <strong>menos de cinco por cento saíam de Salvador para trabalhar</strong>. Esse número é baixo, e a razão é que Salvador é o polo da sua região metropolitana, e não uma cidade-dormitório. O movimento pendular relevante ali é o de entrada, vindo sobretudo de outros municípios vizinhos como Simões Filho e Lauro de Freitas.</p>
<p>Cabe aqui um alerta metodológico que vale para qualquer leitura municipal do Censo. A pesquisa descreve quem <strong>mora</strong> no município, e não quem trabalha nele. Para dimensionar quem chega de fora todos os dias seria preciso ler os microdados dos municípios de origem e usar <code>V6604</code>, que informa o código do município de trabalho. O capítulo não faz isso, e o leitor que precisar dessa conta deve ter em mente que o recorte de leitura muda por completo.</p>
<p>A segunda informação é que praticamente um quarto das pessoas ocupadas trabalhava no próprio domicílio. Esse contingente não realiza deslocamento casa-trabalho e, por construção do questionário, não responde ao quesito de tempo. Antes de calcular qualquer tempo médio, portanto, é preciso saber exatamente quem responde ao quesito:</p>
<p>Cruzamos, entre os que trabalham fora do domicílio, o retorno diário para casa (<code>V0661</code>) com o fato de a pessoa ter ou não respondido ao tempo de deslocamento (<code>V0662</code>). O argumento <code>.drop = FALSE</code> do <code>count()</code>, apresentado no Capítulo 9, é essencial aqui, porque sem ele as combinações que não ocorrem simplesmente não apareceriam na tabela, e são justamente elas que precisamos ver. O <code>pivot_wider()</code> do Capítulo 3 arruma o resultado como um quadro de dupla entrada.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>md_pes <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(V0660 <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"2"</span>, <span class="st">"3"</span>, <span class="st">"4"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">retorna =</span> <span class="fu">factor</span>(V0661, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Retorna diariamente"</span>, <span class="st">"Não retorna diariamente"</span>)),</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">tempo   =</span> <span class="fu">factor</span>(<span class="sc">!</span><span class="fu">is.na</span>(V0662), <span class="at">levels =</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>),</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Respondeu V0662"</span>, <span class="st">"V0662 em branco"</span>))</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(retorna, tempo, <span class="at">.drop =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> tempo, <span class="at">values_from =</span> n) <span class="sc">|&gt;</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Retorno para casa"</span>, <span class="st">"Respondeu `V0662`"</span>, <span class="st">"`V0662` em branco"</span>),</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">"."</span>, <span class="at">decimal.mark =</span> <span class="st">","</span>)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-mob-universo" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mob-universo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;15.3: Registros da amostra de Salvador (BA) que trabalhavam fora do domicílio, segundo o retorno diário para casa (<code>V0661</code>) e a resposta ao tempo de deslocamento (<code>V0662</code>), Censo 2010.
</figcaption>
<div aria-describedby="tbl-mob-universo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Retorno para casa</th>
<th style="text-align: right;">Respondeu <code>V0662</code></th>
<th style="text-align: right;"><code>V0662</code> em branco</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Retorna diariamente</td>
<td style="text-align: right;">46.905</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Não retorna diariamente</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.365</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>As duas casas fora da diagonal valem <strong>exatamente zero</strong>, e é isso que o <code>.drop = FALSE</code> permite enxergar. Nenhum dos 46.905 registros de quem retorna diariamente deixou o tempo em branco, e nenhum dos 2.365 registros de quem não retorna respondeu ao quesito. As duas perguntas delimitam o mesmo conjunto de pessoas, o que confirma que o universo do indicador de tempo é o das pessoas que trabalham fora do domicílio <strong>e</strong> retornam para casa diariamente, exatamente como consta no título das tabelas que o IBGE publica no SIDRA para esse quesito. Quem trabalha em casa, quem trabalha em mais de um município e quem não volta todo dia ficam de fora, e a soma dos três não é desprezível em Salvador.</p>
</section>
<section id="sec-mob-tempo" class="level2" data-number="15.6">
<h2 data-number="15.6" class="anchored" data-anchor-id="sec-mob-tempo"><span class="header-section-number">15.6</span> Tempo de deslocamento</h2>
<p>Fixado o universo, podemos calcular a métrica mais interessante sobre mobilidade do Censo de 2010. O tempo de deslocamento é o indicador de mobilidade mais próximo da experiência cotidiana, e em 2010 ele foi coletado em cinco níveis de natureza categórica ordinal, o que impede calcular uma média ou mediana.</p>
<p>Como fizemos com os domicílios, declaramos o universo filtrando o próprio desenho amostral, e não a tabela de origem. Vale insistir na razão, agora que o recorte é mais delicado. O <code>srvyr</code> trata o subconjunto como domínio e calcula os erros-padrão levando em conta que ele é parte de uma amostra maior, preservando a estratificação, os conglomerados e a correção de população finita declarados no desenho. Um filtro aplicado antes de <code>as_survey_design()</code> faria o <code>srvyr</code> enxergar o subconjunto como se fosse a amostra inteira, produzindo erros-padrão que não correspondem ao desenho efetivamente realizado. A <a href="#tbl-mob-tempo" class="quarto-xref">Tabela&nbsp;<span>15.4</span></a> traz a distribuição pelas cinco faixas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>pa_pes <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(V0662)) <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">faixa =</span> <span class="fu">factor</span>(</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>      V0662,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>, <span class="st">"4"</span>, <span class="st">"5"</span>),</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Até 5 minutos"</span>, <span class="st">"De 6 minutos até meia hora"</span>,</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Mais de meia hora até uma hora"</span>,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Mais de uma hora até duas horas"</span>,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Mais de duas horas"</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(faixa) <span class="sc">|&gt;</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">proporcao =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span> <span class="st">"ci"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Tempo habitual de deslocamento"</span>, <span class="st">"Proporção"</span>,</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"IC 95%, limite inferior"</span>, <span class="st">"IC 95%, limite superior"</span>),</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">decimal.mark =</span> <span class="st">","</span>)</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-mob-tempo" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mob-tempo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;15.4: Distribuição das pessoas que trabalham fora do domicílio e retornam diariamente para casa em Salvador (BA) segundo o tempo habitual de deslocamento até o trabalho, microdados da amostra do Censo 2010.
</figcaption>
<div aria-describedby="tbl-mob-tempo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 35%">
<col style="width: 11%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tempo habitual de deslocamento</th>
<th style="text-align: right;">Proporção</th>
<th style="text-align: right;">IC 95%, limite inferior</th>
<th style="text-align: right;">IC 95%, limite superior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Até 5 minutos</td>
<td style="text-align: right;">0,059</td>
<td style="text-align: right;">0,056</td>
<td style="text-align: right;">0,061</td>
</tr>
<tr class="even">
<td style="text-align: left;">De 6 minutos até meia hora</td>
<td style="text-align: right;">0,335</td>
<td style="text-align: right;">0,330</td>
<td style="text-align: right;">0,340</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mais de meia hora até uma hora</td>
<td style="text-align: right;">0,386</td>
<td style="text-align: right;">0,381</td>
<td style="text-align: right;">0,392</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mais de uma hora até duas horas</td>
<td style="text-align: right;">0,195</td>
<td style="text-align: right;">0,190</td>
<td style="text-align: right;">0,199</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mais de duas horas</td>
<td style="text-align: right;">0,026</td>
<td style="text-align: right;">0,024</td>
<td style="text-align: right;">0,028</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Cerca de quatro em cada dez viagens cabiam em meia hora e <strong>pouco mais de um quinto passava de uma hora</strong>. Esse último grupo é um dos que mais interessa à política pública, porque tempo de deslocamento excessivo é uma forma de privação que se acumula todos os dias e que consome horas que não voltam. Vale dimensionar o quanto essa proporção é alta. A <a href="https://sidra.ibge.gov.br/tabela/3422">Tabela 3422 do SIDRA</a> traz esse mesmo quesito para todos os municípios do país em 2010 e permite situar Salvador entre as capitais. Apenas São Paulo, com 31,0%, e Rio de Janeiro, com 25,3%, registravam proporção maior. A mediana das 27 capitais era de 9,3%, com Curitiba em 10,8%, Porto Alegre em 10,1% e Goiânia em 9,3%, e mesmo capitais populosas como Fortaleza e Recife ficavam em 12,7% e 11,2%. Salvador estava, portanto, entre as três capitais em que o deslocamento casa-trabalho mais consumia tempo, o que dá a medida do que significava atravessar a cidade em hora de pico no período investigado no Censo de 2010.</p>
<p>Convém olhar com o mesmo cuidado para o outro extremo da tabela. As viagens de até meia hora reúnem quase quatro em cada dez pessoas, com a faixa de 6 a 30 minutos concentrando sozinha um terço do total, e seria apressado ler esse resultado como sinal de boa mobilidade. Um tempo curto de deslocamento pode significar que a pessoa mora perto de um bom emprego, mas também pode corresponder ao contrário, que o seu <strong>espaço de atividades</strong> é restrito e que ela trabalha perto de casa por não conseguir custear um deslocamento maior, seja por motorização individual, seja por transporte coletivo.</p>
<p>A literatura de transportes trata o tamanho do espaço de atividades como indicador de risco de exclusão social por essa razão <span class="citation" data-cites="schonfelder2003activity">(<a href="references.html#ref-schonfelder2003activity" role="doc-biblioref">Schönfelder &amp; Axhausen, 2003</a>)</span>, e os estudos sobre exclusão social relacionada ao transporte mostram que a restrição de deslocamento estreita o leque de oportunidades de emprego, estudo e serviços ao alcance da pessoa <span class="citation" data-cites="lucas2012transport vasconcellos2001transporte">(<a href="references.html#ref-lucas2012transport" role="doc-biblioref">Lucas, 2012</a>; <a href="references.html#ref-vasconcellos2001transporte" role="doc-biblioref">Vasconcellos, 2001</a>)</span>.</p>
<p>A <a href="#fig-tempo" class="quarto-xref">Figura&nbsp;<span>15.3</span></a> leva o indicador ao território, somando as duas faixas superiores, compreendendo os indivíduos que se deslocam por mais de uma hora:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Somando as duas faixas acima de uma hora, por área de ponderação:</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>tempo_ap <span class="ot">&lt;-</span> pa_pes <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(V0662)) <span class="sc">|&gt;</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(code_weighting) <span class="sc">|&gt;</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mais_de_uma_hora =</span> <span class="fu">survey_mean</span>(V0662 <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"4"</span>, <span class="st">"5"</span>)))</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Mapa:</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>ap_ssa <span class="sc">|&gt;</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(tempo_ap, <span class="at">by =</span> <span class="fu">join_by</span>(code_weighting)) <span class="sc">|&gt;</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> <span class="dv">100</span> <span class="sc">*</span> mais_de_uma_hora), <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"RdPu"</span>, <span class="at">direction =</span> <span class="dv">1</span>,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>                       <span class="at">name =</span> <span class="st">"% acima de</span><span class="sc">\n</span><span class="st">uma hora"</span>, <span class="at">na.value =</span> <span class="st">"gray90"</span>) <span class="sc">+</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">expand =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  tema_mapa</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-tempo" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-tempo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;15.3: Proporção de trabalhadores com mais de uma hora de deslocamento até o trabalho, por área de ponderação, Salvador (BA), microdados da amostra do Censo 2010.
</figcaption>
<div aria-describedby="fig-tempo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15-mobilidade_files/figure-html/fig-tempo-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>Sem surpresa, as manchas mais escuras estão nas áreas de maior vulnerabilidade socioeconômica do município, que também são as mais distantes dos centros de emprego. Elas formam um bloco contínuo no extremo nordeste da malha urbana. Antes de qualquer leitura mais fina, vale medir o tamanho da variação e confrontá-lo com a incerteza das estimativas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>tempo_ap <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">minimo              =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">min</span>(mais_de_uma_hora),</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">maximo              =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">max</span>(mais_de_uma_hora),</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">largura_media_do_ic =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">mean</span>(<span class="dv">2</span> <span class="sc">*</span> <span class="fl">1.96</span> <span class="sc">*</span> mais_de_uma_hora_se)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  ) </span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  minimo maximo largura_media_do_ic
   &lt;dbl&gt;  &lt;dbl&gt;               &lt;dbl&gt;
1   7.79   50.7                7.34</code></pre>
</div>
</div>
<p>A amplitude é grande, com áreas em que menos de um em cada doze trabalhadores gasta mais de uma hora e áreas em que a proporção passa de metade. A largura média do intervalo de confiança fica bem abaixo dessa diferença, o que significa que o contraste entre os extremos é real, e não ruído amostral. Diferenças pequenas entre áreas vizinhas, porém, continuam exigindo cautela, porque duas áreas separadas por sete pontos percentuais podem ter intervalos que se sobrepõem.</p>
<p>Vale, por fim, confrontar a <a href="#fig-veiculos" class="quarto-xref">Figura&nbsp;<span>15.2</span></a> com a <a href="#fig-tempo" class="quarto-xref">Figura&nbsp;<span>15.3</span></a>, já que ambas usam a mesma amostra, o mesmo ano e o mesmo recorte espacial. As áreas de maior posse de automóvel são, em geral, as de menor tempo de deslocamento, e nesse ponto os dois mapas se espelham.</p>
<p>Descrito o comportamento, passamos à infraestrutura que o sustenta.</p>
</section>
<section id="sec-mob-acessibilidade" class="level2" data-number="15.7">
<h2 data-number="15.7" class="anchored" data-anchor-id="sec-mob-acessibilidade"><span class="header-section-number">15.7</span> A infraestrutura para a acessibilidade</h2>
<p>Agora mudamos a fonte, o ano e a unidade espacial. A Pesquisa Urbanística do Entorno dos Domicílios, apresentada no Capítulo 11, descreve por observação direta as características urbanísticas do trecho de rua em frente a cada domicílio, e é divulgada por setor censitário. Ela não pergunta nada ao morador, o que a torna independente de declaração e a coloca em outro registro de evidência.</p>
<p>Convém ter em mente, desde já, que <strong>o local observada não é a mesma em todos os itens</strong>, conforme a <a href="11-entorno.html#tbl-criterios" class="quarto-xref">Tabela&nbsp;<span>11.2</span></a> do Capítulo 11 detalha. Os itens ligados à via, entre eles a pavimentação, o ponto de ônibus e a sinalização para bicicleta, são observados na face percorrida, na face confrontante e no canteiro central. Já os itens ligados à calçada, que são a existência, o obstáculo e a rampa, são observados <strong>somente na face percorrida</strong>. Percentuais desses dois grupos apresentados lado a lado não descrevem a mesma extensão de espaço público.</p>
<p>Dos dez itens investigados em 2022, seis dizem respeito direto à acessibilidade física no sentido definido na introdução. Dois deles descrevem a via, que são a pavimentação e a sinalização para bicicleta. Três descrevem a calçada, que são a existência, a presença de obstáculo e a rampa para cadeirante. E um descreve um componente da oferta de transporte coletivo, que é o ponto de ônibus ou van.</p>
<p>Além disso, é importante frisar que estes itens registram somente a presença ou a ausência de cada elemento, e nada informam sobre largura, estado de conservação, continuidade ao longo do percurso, declividade ou frequência do serviço, todos determinantes da experiência de quem caminha ou espera o ônibus. Não sustentam, portanto, um diagnóstico completo da infraestrutura física, nem uma avaliação rigorosa de macroacessibilidade, que trata do alcance da rede de transporte na escala da cidade, nem de microacessibilidade, que trata das condições de circulação no percurso imediato. O que eles oferecem são bons primeiros indícios, disponíveis para todos os setores censitários do país e comparáveis entre si, e é assim que devem ser lidos ao longo do capítulo.</p>
<p>Usaremos apenas os dados de 2022 por uma razão metodológica. Conforme vimos na <a href="11-entorno.html#tbl-comparabilidade" class="quarto-xref">Tabela&nbsp;<span>11.5</span></a> do Capítulo 11, somente iluminação pública e bueiro ou boca de lobo mantiveram o mesmo conceito e critério entre os dois censos. Calçada e pavimentação mudaram de definição, a rampa passou a ser investigada apenas nas faces que têm calçada, e nenhum dos itens que interessam a este capítulo admite comparação direta com 2010. Uma série histórica montada com esses números mediria a mudança do questionário, e não a da cidade.</p>
<p>O bloco a ser utilizado é o de <strong>domicílios</strong> do arquivo, e não o de faces de quadra. Essa escolha importa porque contar faces mede extensão de via, enquanto contar domicílios mede quantas moradias estão diante de cada situação, que é o que interessa quando a pergunta é sobre pessoas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Lendo o arquivo de Entorno, no bloco de domicílios:</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>ent_ssa <span class="ot">&lt;-</span> <span class="fu">read_tracts</span>(<span class="at">dataset =</span> <span class="st">"Entorno"</span>, <span class="at">year =</span> <span class="dv">2022</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(code_muni <span class="sc">==</span> salvador) <span class="sc">|&gt;</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(code_tract,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>         domicilios_V05000,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>         <span class="fu">num_range</span>(<span class="st">"domicilios_V050"</span>, <span class="dv">6</span><span class="sc">:</span><span class="dv">8</span>,   <span class="at">width =</span> <span class="dv">2</span>),</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>         <span class="fu">num_range</span>(<span class="st">"domicilios_V050"</span>, <span class="dv">15</span><span class="sc">:</span><span class="dv">29</span>, <span class="at">width =</span> <span class="dv">2</span>)) <span class="sc">|&gt;</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect</span>()</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(ent_ssa)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4531</code></pre>
</div>
</div>
<p>O denominador de todos os indicadores é <code>domicilios_V05000</code>, o total de domicílios particulares permanentes com entorno pesquisado. Não é o total de domicílios do setor, pela razão discutida na <a href="11-entorno.html#sec-entorno-denominador" class="quarto-xref"><span>Seção 11.4</span></a>. Vale medir o quanto o entorno cobre do município antes de calcular qualquer percentual, e para isso precisamos do arquivo Básico, que traz o total de domicílios ocupados e a identificação geográfica de cada setor.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Lendo o arquivo Básico, p/ o total de domicílios ocupados e os bairros:</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>basico_2022 <span class="ot">&lt;-</span> <span class="fu">read_tracts</span>(<span class="at">dataset =</span> <span class="st">"Basico"</span>, <span class="at">year =</span> <span class="dv">2022</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(code_muni <span class="sc">==</span> salvador) <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(code_tract, name_neighborhood, situacao, V0007) <span class="sc">|&gt;</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect</span>()</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(basico_2022)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4542</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">setores_no_basico   =</span> <span class="fu">nrow</span>(basico_2022),</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">setores_com_entorno =</span> <span class="fu">nrow</span>(ent_ssa),</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">dom_ocupados        =</span> <span class="fu">sum</span>(basico_2022<span class="sc">$</span>V0007, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">dom_investigados    =</span> <span class="fu">sum</span>(ent_ssa<span class="sc">$</span>domicilios_V05000, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cobertura =</span> <span class="dv">100</span> <span class="sc">*</span> dom_investigados <span class="sc">/</span> dom_ocupados)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  setores_no_basico setores_com_entorno dom_ocupados dom_investigados cobertura
              &lt;int&gt;               &lt;int&gt;        &lt;dbl&gt;            &lt;dbl&gt;     &lt;dbl&gt;
1              4542                4531       959423           956277      99.7</code></pre>
</div>
</div>
<p>Praticamente todos os domicílios ocupados do município têm entorno pesquisado, o que dá segurança à leitura. Municípios com forte presença rural apresentam cobertura bem menor, conforme vimos no Capítulo 11, e a verificação deve ser refeita a cada caso.</p>
<p>Calculamos agora os indicadores municipais, e eles não cabem todos em uma tabela só. Quatro dos seis itens são perguntados em toda face pesquisada, e o denominador deles é o total de domicílios com entorno pesquisado. Os outros dois, obstáculo e rampa, só são investigados onde existe calçada, e por isso pedem denominador próprio. Começamos pelos quatro primeiros.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Somando todas as colunas do Entorno de uma vez, p/ o município inteiro:</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>totais <span class="ot">&lt;-</span> ent_ssa <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"domicilios_"</span>), \(x) <span class="fu">sum</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Montando a tabela dos quatro itens investigados em toda face:</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Item =</span> <span class="fu">c</span>(<span class="st">"Via pavimentada"</span>, <span class="st">"Ponto de ônibus ou van"</span>,</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>           <span class="st">"Via sinalizada para bicicleta"</span>, <span class="st">"Calçada"</span>),</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Sim  =</span> <span class="fu">c</span>(totais<span class="sc">$</span>domicilios_V05006, totais<span class="sc">$</span>domicilios_V05015,</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>           totais<span class="sc">$</span>domicilios_V05018, totais<span class="sc">$</span>domicilios_V05021),</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Nao  =</span> <span class="fu">c</span>(totais<span class="sc">$</span>domicilios_V05007, totais<span class="sc">$</span>domicilios_V05016,</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>           totais<span class="sc">$</span>domicilios_V05019, totais<span class="sc">$</span>domicilios_V05022),</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Não declarado</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(totais<span class="sc">$</span>domicilios_V05008, totais<span class="sc">$</span>domicilios_V05017,</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>                      totais<span class="sc">$</span>domicilios_V05020, totais<span class="sc">$</span>domicilios_V05023)</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">% com o item</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">100</span> <span class="sc">*</span> Sim <span class="sc">/</span> totais<span class="sc">$</span>domicilios_V05000) <span class="sc">|&gt;</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">1</span>, <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">"."</span>, <span class="at">decimal.mark =</span> <span class="st">","</span>))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-mob-entorno-mun" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mob-entorno-mun-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;15.5: Presença dos itens de infraestrutura do entorno investigados em todas as faces, sobre o total de domicílios com entorno pesquisado, Salvador (BA), Censo 2022.
</figcaption>
<div aria-describedby="tbl-mob-entorno-mun-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 41%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 19%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: right;">Sim</th>
<th style="text-align: right;">Nao</th>
<th style="text-align: right;">Não declarado</th>
<th style="text-align: right;">% com o item</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Via pavimentada</td>
<td style="text-align: right;">935.870</td>
<td style="text-align: right;">17.479</td>
<td style="text-align: right;">2.928</td>
<td style="text-align: right;">97,9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ponto de ônibus ou van</td>
<td style="text-align: right;">79.753</td>
<td style="text-align: right;">873.596</td>
<td style="text-align: right;">2.928</td>
<td style="text-align: right;">8,3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Via sinalizada para bicicleta</td>
<td style="text-align: right;">30.572</td>
<td style="text-align: right;">922.777</td>
<td style="text-align: right;">2.928</td>
<td style="text-align: right;">3,2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Calçada</td>
<td style="text-align: right;">543.881</td>
<td style="text-align: right;">409.468</td>
<td style="text-align: right;">2.928</td>
<td style="text-align: right;">56,9</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>A tabela desenha cenários bastante distintos para a mobilidade motorizada e a ativa (caminhada e bicicleta). A pavimentação está praticamente universalizada, com quase noventa e oito por cento dos domicílios em face de via pavimentada. A calçada cai para pouco mais da metade, o que significa que perto de quatrocentos mil domicílios de Salvador não têm calçada em frente. Como pouco mais de vinte mil domicílios do município estão em face de via sem pavimentação ou sem declaração, a imensa maioria desses quatrocentos mil está diante de uma via pavimentada e sem qualquer separação entre quem anda e quem dirige. E os itens que servem a quem não usa automóvel, como o ponto de ônibus e a via sinalizada para bicicleta, ficam abaixo de dez por cento. Repare ainda que a coluna de não declarados é um resíduo pequeno, de menos de três mil domicílios, o mesmo nos quatro itens.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Aviso</span>Ponto de ônibus na face não é o mesmo que acesso ao transporte
</div>
</div>
<div class="callout-body-container callout-body">
<p>Os oito por cento de ponto de ônibus não medem de forma inequívoca a cobertura do transporte coletivo em Salvador. O objetivo declarado na definição do quesito é “identificar pontos com sinalização visível de parada de transporte público do tipo ônibus/van para embarque e desembarque de passageiros”, com critério <strong>Mínimo</strong> e local de investigação na <strong>face percorrida, na face confrontante e no canteiro central</strong>, quando houver <span class="citation" data-cites="ibge_entorno2022">(<a href="references.html#ref-ibge_entorno2022" role="doc-biblioref">IBGE, 2025</a>)</span>. Basta, portanto, uma sinalização em qualquer dos dois lados da rua, e o outro lado conta tanto quanto o da porta de casa. Por outro lado, nada é observado fora desse trecho, de modo que um ponto situado na esquina seguinte, a poucos minutos de caminhada, não entra na conta daquela face. Todavia, para uma análise mais ampla da acessibilidade proporcionada pelo transporte público, é necessário entender outros aspectos, a exemplo de quais linhas passam por esses pontos e com que frequência os ônibus passam por eles.</p>
</div>
</div>
<p>Passemos aos dois itens restantes. Como o questionário só pergunta por obstáculo e por rampa nas faces em que existe calçada, conforme o fluxo apresentado na <a href="11-entorno.html#sec-entorno-fluxo" class="quarto-xref"><span>Seção 11.2.3.2</span></a>, os domicílios sem calçada não recebem “não” nesses quesitos, e sim “não declarado”. Dividi-los pelo total de domicílios investigados jogaria no denominador quem nunca teve chance de aparecer no numerador, e o percentual resultante misturaria duas carências distintas, a de não ter calçada e a de ter uma calçada sem rampa. O denominador correto é o total de domicílios com calçada, e a própria tabela mostra que ele fecha, porque as colunas de “sim” e “não” somam exatamente esse total em ambos os itens.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Item =</span> <span class="fu">c</span>(<span class="st">"Obstáculo na calçada"</span>, <span class="st">"Rampa para cadeirante"</span>),</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Sim  =</span> <span class="fu">c</span>(totais<span class="sc">$</span>domicilios_V05024, totais<span class="sc">$</span>domicilios_V05027),</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Nao  =</span> <span class="fu">c</span>(totais<span class="sc">$</span>domicilios_V05025, totais<span class="sc">$</span>domicilios_V05028),</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Domicílios com calçada</span><span class="st">`</span> <span class="ot">=</span> totais<span class="sc">$</span>domicilios_V05021</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">% com o item</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">100</span> <span class="sc">*</span> Sim <span class="sc">/</span> <span class="st">`</span><span class="at">Domicílios com calçada</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">1</span>, <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">"."</span>, <span class="at">decimal.mark =</span> <span class="st">","</span>))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-mob-calcada-qualidade" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mob-calcada-qualidade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;15.6: Obstáculo e rampa no entorno dos domicílios de Salvador (BA), calculados sobre o total de domicílios em face com calçada, Censo 2022.
</figcaption>
<div aria-describedby="tbl-mob-calcada-qualidade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 29%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 31%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: right;">Sim</th>
<th style="text-align: right;">Nao</th>
<th style="text-align: right;">Domicílios com calçada</th>
<th style="text-align: right;">% com o item</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Obstáculo na calçada</td>
<td style="text-align: right;">366.700</td>
<td style="text-align: right;">177.181</td>
<td style="text-align: right;">543.881</td>
<td style="text-align: right;">67,4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rampa para cadeirante</td>
<td style="text-align: right;">68.338</td>
<td style="text-align: right;">475.543</td>
<td style="text-align: right;">543.881</td>
<td style="text-align: right;">12,6</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Dois terços das calçadas de Salvador têm alguma obstrução, seja poste, seja degrau, seja mercadoria exposta. A rampa para cadeirante, por sua vez, aparece em pouco mais de um em cada oito domicílios que têm calçada em frente. Como esse subconjunto já é apenas pouco mais da metade dos domicílios investigados, o caminho acessível de ponta a ponta, com calçada e com rampa, é bem mais raro do que qualquer um dos dois indicadores isolados sugere.</p>
<p>Essa é a forma de contar que adotaremos em todo o restante do capítulo sempre que o assunto for a qualidade da calçada.</p>
<section id="sec-mob-mapas" class="level3" data-number="15.7.1">
<h3 data-number="15.7.1" class="anchored" data-anchor-id="sec-mob-mapas"><span class="header-section-number">15.7.1</span> Onde está a infraestrutura</h3>
<p>Levemos os indicadores ao mapa. A leitura das geometrias exige dois cuidados, ambos resolvidos no mesmo bloco de código. O primeiro é descartar o setor <code>292740805100008</code>, que tem 386 km², nenhum morador e nenhuma classificação de situação, porque corresponde à porção da Baía de Todos-os-Santos que está dentro dos limites municipais. É importante frisar que, neste caso, ele só se encontra sobre as águas da baía e não compreende nenhuma porção terrestre habitada<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Mantê-lo comprimiria a cidade em um canto da figura, como aconteceu com a área de ponderação da <a href="#fig-veiculos" class="quarto-xref">Figura&nbsp;<span>15.2</span></a>. O filtro <code>!is.na(situacao)</code> dá conta dele, e as ilhas habitadas permanecem no mapa. O segundo é que a malha de setores censitários do <code>geobr</code> para Salvador traz três setores repartidos em mais de uma linha. Por terem partes desconexas, e é preciso dissolvê-los pelo código com <code>group_by()</code> e <code>summarize()</code>, na forma apresentada no Capítulo 5, para que nenhum setor entre duas vezes nas somas por bairro.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Lendo a malha de setores de 2022:</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>setores_2022 <span class="ot">&lt;-</span> <span class="fu">read_census_tract</span>(</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">code_tract =</span> salvador,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">year       =</span> <span class="dv">2022</span>,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">simplified =</span> <span class="cn">FALSE</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(code_tract)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="do">## Dissolvendo os setores repartidos, descartando o setor da baía e</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="do">## criando os quatro indicadores:</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>ent_geo <span class="ot">&lt;-</span> setores_2022 <span class="sc">|&gt;</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(code_tract) <span class="sc">|&gt;</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(basico_2022, <span class="at">by =</span> <span class="st">"code_tract"</span>) <span class="sc">|&gt;</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(situacao)) <span class="sc">|&gt;</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(ent_ssa, <span class="at">by =</span> <span class="st">"code_tract"</span>) <span class="sc">|&gt;</span></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_pavimentada =</span> <span class="dv">100</span> <span class="sc">*</span> domicilios_V05006 <span class="sc">/</span> domicilios_V05000,</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_calcada     =</span> <span class="dv">100</span> <span class="sc">*</span> domicilios_V05021 <span class="sc">/</span> domicilios_V05000,</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_obstaculo   =</span> <span class="dv">100</span> <span class="sc">*</span> domicilios_V05024 <span class="sc">/</span> domicilios_V05021,</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_rampa       =</span> <span class="dv">100</span> <span class="sc">*</span> domicilios_V05027 <span class="sc">/</span> domicilios_V05021</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(ent_geo)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4541</code></pre>
</div>
</div>
<p>Restam 4.541 setores, que são os 4.542 do arquivo Básico menos o setor da baía. A <a href="#fig-entorno" class="quarto-xref">Figura&nbsp;<span>15.4</span></a> traz quatro indicadores nessa malha. Os dois de cima descrevem o que existe na via e na testada do lote, sobre o total de domicílios investigados. Os dois de baixo descrevem a qualidade da calçada e, por isso, usam como denominador apenas os domicílios que têm calçada, na forma discutida na seção anterior. Faremos a leitura depois de ver a mesma figura em um segundo recorte espacial.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Legenda compacta, para sobrar espaço aos mapas nos quatro painéis:</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>tema_legenda <span class="ot">&lt;-</span> <span class="fu">theme</span>(</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.key.width  =</span> <span class="fu">unit</span>(<span class="fl">0.30</span>, <span class="st">"cm"</span>),</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.key.height =</span> <span class="fu">unit</span>(<span class="fl">0.55</span>, <span class="st">"cm"</span>),</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.title      =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">7</span>),</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.text       =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>),</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.margin     =</span> <span class="fu">margin</span>(<span class="at">l =</span> <span class="dv">0</span>, <span class="at">r =</span> <span class="dv">0</span>),</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">plot.subtitle     =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>)</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="do">## Um mapa por indicador:</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>e1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ent_geo) <span class="sc">+</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> p_pavimentada), <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"Greys"</span>, <span class="at">direction =</span> <span class="dv">1</span>, <span class="at">name =</span> <span class="st">"%"</span>,</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>                       <span class="at">na.value =</span> <span class="st">"gray95"</span>, <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">expand =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">"Via pavimentada"</span>) <span class="sc">+</span></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>  tema_mapa <span class="sc">+</span> tema_legenda</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>e2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ent_geo) <span class="sc">+</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> p_calcada), <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"BuGn"</span>, <span class="at">direction =</span> <span class="dv">1</span>, <span class="at">name =</span> <span class="st">"%"</span>,</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>                       <span class="at">na.value =</span> <span class="st">"gray95"</span>, <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">expand =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">"Calçada"</span>) <span class="sc">+</span></span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a>  tema_mapa <span class="sc">+</span> tema_legenda</span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a>e3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ent_geo) <span class="sc">+</span></span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> p_obstaculo), <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"OrRd"</span>, <span class="at">direction =</span> <span class="dv">1</span>, <span class="at">name =</span> <span class="st">"%"</span>,</span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a>                       <span class="at">na.value =</span> <span class="st">"gray95"</span>, <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">expand =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">"Obstáculo, entre os com calçada"</span>) <span class="sc">+</span></span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a>  tema_mapa <span class="sc">+</span> tema_legenda</span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-33"><a href="#cb33-33" aria-hidden="true" tabindex="-1"></a>e4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ent_geo) <span class="sc">+</span></span>
<span id="cb33-34"><a href="#cb33-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> p_rampa), <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb33-35"><a href="#cb33-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"Purples"</span>, <span class="at">direction =</span> <span class="dv">1</span>, <span class="at">name =</span> <span class="st">"%"</span>,</span>
<span id="cb33-36"><a href="#cb33-36" aria-hidden="true" tabindex="-1"></a>                       <span class="at">na.value =</span> <span class="st">"gray95"</span>) <span class="sc">+</span></span>
<span id="cb33-37"><a href="#cb33-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">expand =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">"Rampa, entre os com calçada"</span>) <span class="sc">+</span></span>
<span id="cb33-38"><a href="#cb33-38" aria-hidden="true" tabindex="-1"></a>  tema_mapa <span class="sc">+</span> tema_legenda</span>
<span id="cb33-39"><a href="#cb33-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-40"><a href="#cb33-40" aria-hidden="true" tabindex="-1"></a><span class="do">## Composição em dois por dois:</span></span>
<span id="cb33-41"><a href="#cb33-41" aria-hidden="true" tabindex="-1"></a>(e1 <span class="sc">+</span> e2) <span class="sc">/</span> (e3 <span class="sc">+</span> e4)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-entorno" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-entorno-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;15.4: Indicadores de acessibilidade do entorno por setor censitário, Salvador (BA), Censo 2022. Nos painéis superiores, percentuais sobre os domicílios com entorno pesquisado. Nos inferiores, sobre os domicílios com calçada.
</figcaption>
<div aria-describedby="fig-entorno-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15-mobilidade_files/figure-html/fig-entorno-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>O setor censitário é a maior resolução disponível e, com 4.541 unidades, produz uma figura granulada em que a leitura de conjunto compete com o detalhe. Vale, por isso, refazer a mesma figura por bairro. Salvador tem os bairros preenchidos nos agregados, ao contrário do que vimos em Goiânia no Capítulo 12, e são 170 no total. Agregamos os indicadores somando numeradores e denominadores antes de dividir, conforme sempre fizemos.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Somando numeradores e denominadores por bairro antes de dividir:</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>bairros_ent <span class="ot">&lt;-</span> ent_geo <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(name_neighborhood)) <span class="sc">|&gt;</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name_neighborhood) <span class="sc">|&gt;</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">investigados =</span> <span class="fu">sum</span>(domicilios_V05000, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">pavimentada  =</span> <span class="fu">sum</span>(domicilios_V05006, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">calcada      =</span> <span class="fu">sum</span>(domicilios_V05021, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">obstaculo    =</span> <span class="fu">sum</span>(domicilios_V05024, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">rampa        =</span> <span class="fu">sum</span>(domicilios_V05027, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_pavimentada =</span> <span class="dv">100</span> <span class="sc">*</span> pavimentada <span class="sc">/</span> investigados,</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_calcada     =</span> <span class="dv">100</span> <span class="sc">*</span> calcada <span class="sc">/</span> investigados,</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_obstaculo   =</span> <span class="dv">100</span> <span class="sc">*</span> obstaculo <span class="sc">/</span> calcada,</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_rampa       =</span> <span class="dv">100</span> <span class="sc">*</span> rampa <span class="sc">/</span> calcada</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>A geometria dos bairros sai da própria malha de setores, dissolvida pelo nome do bairro com <code>group_by()</code> e <code>summarize()</code>, na forma usada no Capítulo 14, com a <code>st_make_valid()</code> antes para corrigir geometrias inválidas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Dissolvendo os setores por bairro e juntando os indicadores:</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>bairros_geo <span class="ot">&lt;-</span> ent_geo <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(name_neighborhood)) <span class="sc">|&gt;</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_make_valid</span>() <span class="sc">|&gt;</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name_neighborhood) <span class="sc">|&gt;</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(bairros_ent, <span class="at">by =</span> <span class="st">"name_neighborhood"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Os quatro painéis da <a href="#fig-entorno-bairros" class="quarto-xref">Figura&nbsp;<span>15.5</span></a> são os mesmos da <a href="#fig-entorno" class="quarto-xref">Figura&nbsp;<span>15.4</span></a>, com as mesmas paletas e as mesmas escalas, de modo que a comparação entre as duas figuras é direta.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Os mesmos quatro mapas, agora por bairro:</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(bairros_geo) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> p_pavimentada), <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"Greys"</span>, <span class="at">direction =</span> <span class="dv">1</span>, <span class="at">name =</span> <span class="st">"%"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">na.value =</span> <span class="st">"gray95"</span>, <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">expand =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">"Via pavimentada"</span>) <span class="sc">+</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  tema_mapa <span class="sc">+</span> tema_legenda</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>b2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(bairros_geo) <span class="sc">+</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> p_calcada), <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"BuGn"</span>, <span class="at">direction =</span> <span class="dv">1</span>, <span class="at">name =</span> <span class="st">"%"</span>,</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>                       <span class="at">na.value =</span> <span class="st">"gray95"</span>, <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">expand =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">"Calçada"</span>) <span class="sc">+</span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>  tema_mapa <span class="sc">+</span> tema_legenda</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>b3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(bairros_geo) <span class="sc">+</span></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> p_obstaculo), <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"OrRd"</span>, <span class="at">direction =</span> <span class="dv">1</span>, <span class="at">name =</span> <span class="st">"%"</span>,</span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>                       <span class="at">na.value =</span> <span class="st">"gray95"</span>, <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">expand =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">"Obstáculo, entre os com calçada"</span>) <span class="sc">+</span></span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>  tema_mapa <span class="sc">+</span> tema_legenda</span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>b4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(bairros_geo) <span class="sc">+</span></span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> p_rampa), <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"Purples"</span>, <span class="at">direction =</span> <span class="dv">1</span>, <span class="at">name =</span> <span class="st">"%"</span>,</span>
<span id="cb36-26"><a href="#cb36-26" aria-hidden="true" tabindex="-1"></a>                       <span class="at">na.value =</span> <span class="st">"gray95"</span>, <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb36-27"><a href="#cb36-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">expand =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">subtitle =</span> <span class="st">"Rampa, entre os com calçada"</span>) <span class="sc">+</span></span>
<span id="cb36-28"><a href="#cb36-28" aria-hidden="true" tabindex="-1"></a>  tema_mapa <span class="sc">+</span> tema_legenda</span>
<span id="cb36-29"><a href="#cb36-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-30"><a href="#cb36-30" aria-hidden="true" tabindex="-1"></a><span class="do">## Composição em dois por dois:</span></span>
<span id="cb36-31"><a href="#cb36-31" aria-hidden="true" tabindex="-1"></a>(b1 <span class="sc">+</span> b2) <span class="sc">/</span> (b3 <span class="sc">+</span> b4)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-entorno-bairros" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-entorno-bairros-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;15.5: Indicadores de acessibilidade do entorno por bairro, Salvador (BA), Censo 2022. Nos painéis superiores, percentuais sobre os domicílios com entorno pesquisado. Nos inferiores, sobre os domicílios com calçada.
</figcaption>
<div aria-describedby="fig-entorno-bairros-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="15-mobilidade_files/figure-html/fig-entorno-bairros-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>Com as duas figuras à vista, podemos ler os quatro indicadores de uma vez. A <strong>pavimentação</strong> confirma no território o que a tabela municipal já indicava, com quase toda a mancha urbana no tom mais escuro da escala. As exceções são poucas e localizadas, e a agregação por bairro as isola bem, com destaque para a mancha da porção norte da cidade, sobretudo nos bairros Cassange, Areia Branca e Itinga. Cassange é o caso mais pronunciado entre os bairros de terra firme. Com ocupação mais recente, evidenciada no aumento expressivo da população entre os dois últimos censos, tem pouco mais de setenta por cento dos domicílios em face de via pavimentada, contra os 97,9% do município. A Ilha de Maré, com metade dos domicílios, é exceção de outra natureza, já que a questão ali não é a data da ocupação.</p>
<p>A <strong>calçada</strong> muda completamente a figura, e nela reaparece a dicotomia socioespacial anunciada na introdução. Uma faixa quase contínua de tom escuro acompanha a orla atlântica e a ponta sul da península, com valores próximos de cem por cento, enquanto o miolo e boa parte do Subúrbio Ferroviário aparecem nos tons mais claros. É no mapa por bairro que essa faixa se fecha e vira um bloco reconhecível. A separação entre quem anda e quem dirige, portanto, existe sobretudo onde moram os grupos de maior renda, e falta justamente onde a dependência do deslocamento a pé é maior.</p>
<p>Os dois painéis inferiores repetem parcialmente esse desenho. O <strong>obstáculo</strong> é escuro em quase toda a cidade, com setores inteiros em que todas as calçadas pesquisadas têm alguma obstrução, mas com maior predominância no miolo e no Subúrbio Ferroviário. A leitura que ele autoriza também carrega a desigualdade territorial, mas também revela um padrão construtivo generalizado, já que onde a calçada existe ela costuma estar obstruída, em maior ou menor grau ao longo de toda a cidade. A <strong>rampa</strong> é o item mais escasso do conjunto, e os dois painéis ficam quase todos no tom mais claro da escala. Onde ela é mais frequente, tende a ser no eixo que vai dos bairros da Pituba ao Imbuí e em outros bairros da orla atlântica, exatamente onde a cobertura de calçada é maior, de modo que a desigualdade da calçada se reproduz e se agrava na sua acessibilidade.</p>
<p>Passemos aos extremos. Na <a href="#tbl-mob-entorno-bairro" class="quarto-xref">Tabela&nbsp;<span>15.7</span></a>, mantemos apenas os bairros com ao menos quinhentos domicílios investigados, para que percentuais calculados sobre denominadores muito pequenos não dominem as pontas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Mantendo só os bairros com ao menos 500 domicílios investigados:</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>bairros_500 <span class="ot">&lt;-</span> bairros_ent <span class="sc">|&gt;</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(investigados <span class="sc">&gt;=</span> <span class="dv">500</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Juntando os 4 maiores com os 6 menores em % com calçada:</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  bairros_500 <span class="sc">|&gt;</span> <span class="fu">slice_max</span>(p_calcada, <span class="at">n =</span> <span class="dv">4</span>),</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  bairros_500 <span class="sc">|&gt;</span> <span class="fu">slice_min</span>(p_calcada, <span class="at">n =</span> <span class="dv">6</span>)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name_neighborhood, investigados, p_pavimentada, p_calcada, p_rampa) <span class="sc">|&gt;</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Bairro"</span>, <span class="st">"Domicílios investigados"</span>, <span class="st">"% com via pavimentada"</span>,</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"% com calçada"</span>, <span class="st">"% com rampa, entre os com calçada"</span>),</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">1</span>,</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">"."</span>, <span class="at">decimal.mark =</span> <span class="st">","</span>)</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-mob-entorno-bairro" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mob-entorno-bairro-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;15.7: Bairros de Salvador (BA) com as menores e as maiores proporções de domicílios com calçada, entre os que possuem ao menos quinhentos domicílios investigados, Censo 2022.
</figcaption>
<div aria-describedby="tbl-mob-entorno-bairro-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 21%">
<col style="width: 20%">
<col style="width: 12%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Bairro</th>
<th style="text-align: right;">Domicílios investigados</th>
<th style="text-align: right;">% com via pavimentada</th>
<th style="text-align: right;">% com calçada</th>
<th style="text-align: right;">% com rampa, entre os com calçada</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Chame-Chame</td>
<td style="text-align: right;">968</td>
<td style="text-align: right;">100,0</td>
<td style="text-align: right;">100,0</td>
<td style="text-align: right;">0,0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Amaralina</td>
<td style="text-align: right;">1.635</td>
<td style="text-align: right;">100,0</td>
<td style="text-align: right;">99,9</td>
<td style="text-align: right;">26,3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Itaigara</td>
<td style="text-align: right;">3.495</td>
<td style="text-align: right;">100,0</td>
<td style="text-align: right;">99,9</td>
<td style="text-align: right;">27,0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Horto Florestal</td>
<td style="text-align: right;">2.823</td>
<td style="text-align: right;">100,0</td>
<td style="text-align: right;">99,9</td>
<td style="text-align: right;">18,1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ilha de Maré</td>
<td style="text-align: right;">1.444</td>
<td style="text-align: right;">50,8</td>
<td style="text-align: right;">1,7</td>
<td style="text-align: right;">0,0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Engomadeira</td>
<td style="text-align: right;">3.446</td>
<td style="text-align: right;">98,2</td>
<td style="text-align: right;">5,1</td>
<td style="text-align: right;">0,0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Palestina</td>
<td style="text-align: right;">1.942</td>
<td style="text-align: right;">97,7</td>
<td style="text-align: right;">5,4</td>
<td style="text-align: right;">0,0</td>
</tr>
<tr class="even">
<td style="text-align: left;">São Gonçalo</td>
<td style="text-align: right;">5.789</td>
<td style="text-align: right;">99,7</td>
<td style="text-align: right;">14,9</td>
<td style="text-align: right;">0,0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Calabetão</td>
<td style="text-align: right;">2.780</td>
<td style="text-align: right;">97,9</td>
<td style="text-align: right;">15,4</td>
<td style="text-align: right;">14,1</td>
</tr>
<tr class="even">
<td style="text-align: left;">São Marcos</td>
<td style="text-align: right;">9.159</td>
<td style="text-align: right;">97,1</td>
<td style="text-align: right;">16,0</td>
<td style="text-align: right;">0,9</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>O contraste entre as duas pontas é o de uma cidade inteira contra outra. Nos bairros do topo, a calçada é praticamente universal. Nos da base, ela existe no entorno de menos de um sexto dos domicílios, e em um deles quase não existe.</p>
<p>Esse caso extremo é a Ilha de Maré, e ele merece leitura própria porque combina duas carências de naturezas distintas. A coluna de pavimentação mostra que metade dos domicílios da ilha está em face de via pavimentada, contra praticamente cem por cento nos demais bairros da tabela. Nos outros bairros da base, a via foi asfaltada e a calçada não veio junto. Na Ilha de Maré, boa parte da via sequer foi pavimentada. São dois estágios diferentes de provisão de infraestrutura, e o indicador de calçada isolado os confundiria.</p>
</section>
</section>
<section id="sec-mob-sintese" class="level2" data-number="15.8">
<h2 data-number="15.8" class="anchored" data-anchor-id="sec-mob-sintese"><span class="header-section-number">15.8</span> Síntese</h2>
<p>O capítulo percorreu as duas perguntas anunciadas no título, cada uma com o produto do Censo que a responde. Do lado do <strong>comportamento</strong>, os microdados da amostra de 2010 mostraram uma Salvador em que menos de três em cada dez domicílios tinham automóvel, com variação de menos de um por cento a quase oitenta e cinco por cento entre áreas de ponderação, e em que pouco mais de um quinto de quem se desloca gastava mais de uma hora para chegar ao trabalho. Esse indicador também é desigual no território, indo de menos de oito por cento a mais de metade dos trabalhadores conforme a área, com os piores tempos nas porções mais distantes dos centros de emprego. Menos de cinco por cento dos ocupados saíam do município para trabalhar, o que é próprio de um polo metropolitano e não de uma cidade-dormitório.</p>
<p>Do lado da <strong>acessibilidade</strong>, o Entorno de 2022 descreveu uma cidade quase inteiramente pavimentada, com 97,9% dos domicílios em face de via pavimentada, e ao mesmo tempo com calçada em apenas 56,9% deles. Entre os que têm calçada, dois terços convivem com algum obstáculo e apenas 12,6% contam com rampa para cadeirante. Os mapas por setor e por bairro mostraram que a pavimentação é praticamente uniforme, com carência concentrada na porção norte de ocupação mais recente, enquanto a calçada reproduz a divisão socioespacial entre a orla atlântica e a ponta sul, de um lado, e o miolo e o Subúrbio Ferroviário, de outro. A distância entre as duas pontas é grande, indo de praticamente nenhuma calçada na Ilha de Maré à cobertura integral em bairros da orla.</p>
<p>Quatro cuidados de método atravessam esses resultados. O primeiro é o do <strong>universo</strong>, porque o tempo de deslocamento só se aplica a quem trabalha fora de casa e retorna diariamente para ela, e calcular a média sobre todos os ocupados produziria um número que não descreve ninguém. O segundo é o do <strong>denominador</strong>, porque obstáculo e rampa só são investigados onde existe calçada, e contá-los sobre o total de domicílios pesquisados jogaria no denominador quem nunca teve chance de aparecer no numerador. O terceiro é o da <strong>comparabilidade</strong>, porque montar uma série histórica de calçada entre 2010 e 2022 mediria a mudança do conceito, e não a da cidade. O quarto é o da <strong>unidade espacial</strong>, já que a mesma figura desenhada por setor e por bairro deixa claro que agregar reduz o ruído e ajuda a nomear os lugares, sem criar padrão onde não havia.</p>
<p>Fica, por fim, o limite do que o Censo alcança. Os seis itens do Entorno registram presença e ausência, e nada dizem sobre largura, conservação, continuidade ou frequência do serviço. Eles descrevem a camada física sobre a qual a acessibilidade se apoia, e não a acessibilidade no sentido estrito, que depende da rede de transporte e da localização das oportunidades. Quando os microdados de 2022 forem divulgados, o quesito de modo de transporte permitirá acrescentar a essa camada física a divisão modal de quem a percorre.</p>
<p>O capítulo seguinte trata da renda e do trabalho, que são, ao mesmo tempo, o destino da maior parte desses deslocamentos e o recurso que determina quais deles são possíveis.</p>
</section>
<section id="sec-mob-exercicios" class="level2" data-number="15.9">
<h2 data-number="15.9" class="anchored" data-anchor-id="sec-mob-exercicios"><span class="header-section-number">15.9</span> Exercícios</h2>
<ol type="1">
<li><p>Reproduza o indicador de deslocamento acima de uma hora para um município que seja periferia de região metropolitana, e não polo, e compare a distribuição das cinco faixas de <code>V0662</code> com a de Salvador. Relacione a diferença encontrada com o que a variável <code>V0660</code> informa sobre o local de trabalho em cada um dos dois municípios.</p></li>
<li><p>A <a href="#tbl-mob-universo" class="quarto-xref">Tabela&nbsp;<span>15.3</span></a> mostrou que o quesito de tempo só é respondido por quem trabalha fora do domicílio e retorna diariamente. Calcule, para Salvador, que proporção do total de pessoas ocupadas fica fora desse universo e decomponha esse total entre os três motivos de exclusão. Discuta o efeito que teria sobre o indicador tratar os excluídos como se tivessem tempo de deslocamento igual a zero.</p></li>
<li><p>A <a href="#tbl-mob-calcada-qualidade" class="quarto-xref">Tabela&nbsp;<span>15.6</span></a> calculou a rampa sobre os domicílios com calçada. Calcule também, por bairro, a versão que usa como denominador o total de domicílios investigados, identifique os bairros em que a diferença entre as duas versões é maior e explique o que caracteriza esses bairros.</p></li>
<li><p>Leia do arquivo Pessoas dos agregados de 2022 as variáveis <code>demografia_V01040</code> e <code>demografia_V01041</code>, que trazem a população de 60 a 69 anos e a de 70 anos ou mais, e calcule a proporção de pessoas nessa faixa em cada setor censitário de Salvador. Selecione então os setores que estão, ao mesmo tempo, entre os vinte e cinco por cento mais envelhecidos e entre os vinte e cinco por cento de menor cobertura de calçada. Mapeie-os, identifique a que bairros pertencem e discuta por que esse recorte é mais útil para orientar uma intervenção de acessibilidade universal do que a média municipal.</p></li>
<li><p>O bloco de faces de quadra do arquivo de Entorno traz os mesmos seis itens usados neste capítulo, com denominador em faces em vez de domicílios. Recalcule os indicadores municipais pelas faces e compare com os da <a href="#tbl-mob-entorno-mun" class="quarto-xref">Tabela&nbsp;<span>15.5</span></a>. Explique por que os dois conjuntos de percentuais diferem e em que situação cada um é o mais adequado.</p></li>
<li><p>Usando a <a href="#tbl-mob-edicoes" class="quarto-xref">Tabela&nbsp;<span>15.1</span></a>, escreva duas listas. Na primeira, as perguntas de mobilidade que só poderão ser respondidas depois da divulgação dos microdados de 2022. Na segunda, as que deixaram de ser respondíveis para sempre. Para cada item da segunda lista, indique que outra fonte de dados poderia substituir o Censo.</p></li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-ibge_entorno2022" class="csl-entry" role="listitem">
IBGE. (2025). <em>Características Urbanísticas do Entorno dos Domicílios: <span>Censo Demográfico</span> 2022</em>. IBGE. <a href="https://biblioteca.ibge.gov.br/visualizacao/livros/liv102168.pdf">https://biblioteca.ibge.gov.br/visualizacao/livros/liv102168.pdf</a>
</div>
<div id="ref-lucas2012transport" class="csl-entry" role="listitem">
Lucas, K. (2012). Transport and social exclusion: Where are we now? <em>Transport Policy</em>, <em>20</em>, 105–113. <a href="https://doi.org/10.1016/j.tranpol.2012.01.013">https://doi.org/10.1016/j.tranpol.2012.01.013</a>
</div>
<div id="ref-schonfelder2003activity" class="csl-entry" role="listitem">
Schönfelder, S., &amp; Axhausen, K. W. (2003). Activity spaces: Measures of social exclusion? <em>Transport Policy</em>, <em>10</em>(4), 273–286. <a href="https://doi.org/10.1016/j.tranpol.2003.07.002">https://doi.org/10.1016/j.tranpol.2003.07.002</a>
</div>
<div id="ref-vasconcellos2001transporte" class="csl-entry" role="listitem">
Vasconcellos, E. A. (2001). <em>Transporte urbano, espaço e equidade: Análise das políticas públicas</em>. Annablume.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Lembre-se de instalá-los com <code>install.packages()</code> caso ainda não o tenha feito<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>diferentemente da área de ponderação <code>2927408005038</code> que contém as águas da baía e outros dois bairros, Paripe e São Tomé<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/pedreirajr\.github\.io\/rcensolivro\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./14-saneamento.html" class="pagination-link" aria-label="Saneamento e Drenagem Urbana">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Saneamento e Drenagem Urbana</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./16-renda-e-trabalho.html" class="pagination-link" aria-label="Renda e Trabalho">
        <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Renda e Trabalho</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Jorge Ubirajara Pedreira Junior. Todos os direitos reservados.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://github.com/pedreirajr/rcensolivro/blob/main/LICENSE">Licença de uso</a></p>
</div>
  </div>
</footer>




</body></html>